-- RATIONAL ROSE GENERATION
-- ALTER TABLE IF EXISTS T_SortePieceDetache DROP CONSTRAINT IF EXISTS FK_T_SortePieceDetache49;
-- ALTER TABLE IF EXISTS T_Place DROP CONSTRAINT IF EXISTS FK_T_Place48;
-- ALTER TABLE IF EXISTS T_SortePieceCommandee DROP CONSTRAINT IF EXISTS FK_T_SortePieceCommandee55;
-- ALTER TABLE IF EXISTS T_SortePieceCommandee DROP CONSTRAINT IF EXISTS FK_T_SortePieceCommandee53;
-- ALTER TABLE IF EXISTS T_Reparation DROP CONSTRAINT IF EXISTS FK_T_Reparation56;
-- ALTER TABLE IF EXISTS T_Service DROP CONSTRAINT IF EXISTS FK_T_Service50;
-- ALTER TABLE IF EXISTS T_Service DROP CONSTRAINT IF EXISTS FK_T_Service46;
-- ALTER TABLE IF EXISTS T_Client DROP CONSTRAINT IF EXISTS FK_T_Client47;
-- ALTER TABLE IF EXISTS T_Parking DROP CONSTRAINT IF EXISTS FK_T_Parking54;
-- ALTER TABLE IF EXISTS T_Parking DROP CONSTRAINT IF EXISTS FK_T_Parking51;
-- DROP TABLE IF EXISTS T_ModePayment;
-- DROP TABLE IF EXISTS T_SortePieceDetache;
-- DROP TABLE IF EXISTS T_Place;
-- DROP TABLE IF EXISTS T_SortePieceCommandee;
-- DROP TABLE IF EXISTS T_Reparation;
-- DROP TABLE IF EXISTS T_Service;
-- DROP TABLE IF EXISTS T_Garage;
-- DROP TABLE IF EXISTS T_Client;
-- DROP TABLE IF EXISTS T_Parking;
CREATE TABLE T_Reparation (
	tempMainDoeuvre DOUBLE PRECISION NOT NULL,
	prixTotal DOUBLE PRECISION NOT NULL,
	serviceID VARCHAR (255) NOT NULL,
	CONSTRAINT PK_T_Reparation54 PRIMARY KEY (serviceID)
);
CREATE INDEX TC_T_Reparation124 ON T_Reparation (serviceID);
CREATE TABLE T_Service (
	serviceID VARCHAR (255) NOT NULL,
	date DATE NOT NULL,
	modePay SMALLINT NOT NULL,
	numClient INTEGER NOT NULL,
	id VARCHAR (255) NOT NULL,
	CONSTRAINT PK_T_Service47 PRIMARY KEY (serviceID)
);
CREATE INDEX TC_T_Service125 ON T_Service (id);
CREATE INDEX TC_T_Service126 ON T_Service (numClient);
CREATE TABLE T_SortePieceDetache (
	codeProduit INTEGER NOT NULL,
	prixUnitaire DOUBLE PRECISION NOT NULL,
	quantiteDisponible INTEGER NOT NULL,
	quantiteMin INTEGER NOT NULL,
	quantiteCommandee INTEGER NOT NULL,
	id VARCHAR (255) NOT NULL,
	CONSTRAINT PK_T_SortePieceDetache48 PRIMARY KEY (codeProduit)
);
CREATE INDEX TC_T_SortePieceDetache129 ON T_SortePieceDetache (id);
CREATE TABLE T_SortePieceCommandee (
	quantiteDemande INTEGER NOT NULL,
	T_SortePieceCommandee_ID INTEGER NOT NULL,
	codeProduit INTEGER NOT NULL,
	serviceID VARCHAR (255) NOT NULL,
	CONSTRAINT PK_T_SortePieceCommandee52 PRIMARY KEY (T_SortePieceCommandee_ID)
);
CREATE INDEX TC_T_SortePieceCommandee127 ON T_SortePieceCommandee (serviceID);
CREATE INDEX TC_T_SortePieceCommandee128 ON T_SortePieceCommandee (codeProduit);
CREATE TABLE T_Parking (
	prixDeLocation DOUBLE PRECISION NOT NULL,
	numPlace INTEGER NOT NULL,
	serviceID VARCHAR (255) NOT NULL,
	CONSTRAINT PK_T_Parking53 PRIMARY KEY (serviceID)
);
CREATE INDEX TC_T_Parking123 ON T_Parking (numPlace);
CREATE INDEX TC_T_Parking122 ON T_Parking (serviceID);
CREATE TABLE T_Place (
	numPlace INTEGER NOT NULL,
	occupee SMALLINT NOT NULL,
	id VARCHAR (255) NOT NULL,
	CONSTRAINT PK_T_Place46 PRIMARY KEY (numPlace)
);
CREATE INDEX TC_T_Place121 ON T_Place (id);
CREATE TABLE T_Client (
	numClient INTEGER NOT NULL,
	name VARCHAR (255) NOT NULL,
	adresse VARCHAR (255) NOT NULL,
	id VARCHAR (255) NOT NULL,
	CONSTRAINT PK_T_Client44 PRIMARY KEY (numClient)
);
CREATE INDEX TC_T_Client120 ON T_Client (id);
CREATE TABLE T_Garage (
	id VARCHAR (255) NOT NULL,
	prixMainDoeuvre DOUBLE PRECISION NOT NULL,
	CONSTRAINT PK_T_Garage45 PRIMARY KEY (id)
);
CREATE TABLE T_ModePayment (
	immediate VARCHAR (255) NOT NULL,
	diffre VARCHAR (255) NOT NULL,
	T_ModePayment_ID INTEGER NOT NULL,
	CONSTRAINT PK_T_ModePayment49 PRIMARY KEY (T_ModePayment_ID)
);
ALTER TABLE T_SortePieceDetache
ADD CONSTRAINT FK_T_SortePieceDetache49 FOREIGN KEY (id) REFERENCES T_Garage (id) ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE T_Place
ADD CONSTRAINT FK_T_Place48 FOREIGN KEY (id) REFERENCES T_Garage (id) ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE T_SortePieceCommandee
ADD CONSTRAINT FK_T_SortePieceCommandee55 FOREIGN KEY (serviceID) REFERENCES T_Reparation (serviceID) ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE T_SortePieceCommandee
ADD CONSTRAINT FK_T_SortePieceCommandee53 FOREIGN KEY (codeProduit) REFERENCES T_SortePieceDetache (codeProduit) ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE T_Reparation
ADD CONSTRAINT FK_T_Reparation56 FOREIGN KEY (serviceID) REFERENCES T_Service (serviceID) ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE T_Service
ADD CONSTRAINT FK_T_Service50 FOREIGN KEY (id) REFERENCES T_Garage (id) ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE T_Service
ADD CONSTRAINT FK_T_Service46 FOREIGN KEY (numClient) REFERENCES T_Client (numClient) ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE T_Client
ADD CONSTRAINT FK_T_Client47 FOREIGN KEY (id) REFERENCES T_Garage (id) ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE T_Parking
ADD CONSTRAINT FK_T_Parking54 FOREIGN KEY (serviceID) REFERENCES T_Service (serviceID) ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE T_Parking
ADD CONSTRAINT FK_T_Parking51 FOREIGN KEY (numPlace) REFERENCES T_Place (numPlace) ON DELETE NO ACTION ON UPDATE NO ACTION;
-- ADDED LATER
DROP TABLE IF EXISTS users;
CREATE TABLE users (
	id INTEGER UNSIGNED PRIMARY KEY NOT NULL AUTO_INCREMENT UNIQUE,
	user VARCHAR(24) NOT NULL,
	pass VARCHAR(24) NOT NULL,
	type CHAR(4) NOT NULL check (type in ('emp', 'rsp'))
);
INSERT INTO users
VALUES (NULL, 'emp', 'emp', 'emp'),
	(NULL, 'rsp', 'rsp', 'rsp');
INSERT INTO T_Garage
VALUES("g1", 10000);